=pod

=head1 NAME

Mite::Manual::Missing - Moose features not supported by Mite

=head1 MANUAL

=head2 Roles

Mite does not offer roles, but here are some ways you can achieve role-like
results with Mite.

=over

=item 1.

Use L<Exporter> to create a role, and then import methods from it into your
classes. It's not really what Exporter is for, but it ought to work.

Advantages: only core modules.

Disadvantages: no attributes, nor method modifiers which will apply to the
consuming class.

=item 2.

Use multiple inheritance. Create your role as a Mite class and inherit from
it instead.

Advantages: only core modules; allows the "role" to define attributes.

Disadvantages: no method modifiers which will apply to the consuming class,
and multiple inheritance hierarchies can get complicated.

=item 3.

Delegate instead of composing. Mite supports C<handles>.

Advantages: only core modules.

Disadvantages: not that role-like, but still a way of bundling up
functionality.

=item 4.

Use L<Role::Tiny>. Role::Tiny roles should work fine with Mite, but you
would need to add Role::Tiny to your project's list of dependencies.

Advantages: a real implementation of roles, method modifiers which will
apply to the consuming class.

Disadvantages: a non-core dependency, and no ability to define attributes.

=item 5.

Upgrade to L<Moo> or L<Moose>. 

=back

=head2 Native Attribute Traits

L<Sub::HandlesVia> 0.026 and above should work with Mite classes. You need
to make sure the Mite shim is loaded I<before> Sub::HandlesVia.

    package Your::Project::Class;
    use Your::Project::Mite;
    use Sub::HandlesVia;
    
    has numbers => (
        is          => 'lazy',
        builder     => sub { [] },
        isa         => 'ArrayRef[Int]',
        handles_via => 'Array',
        handles     => {
            add_number => 'push',
            pop_number => 'pop',
        },
    );
    
    1;

=head2 The Meta-Object Protocol

Upgrade to L<Moose> if you need this.

=head1 BUGS

Please report any bugs to L<https://github.com/tobyink/p5-mite/issues>.

=head1 AUTHOR

Michael G Schwern E<lt>mschwern@cpan.orgE<gt>.

Toby Inkster E<lt>tobyink@cpan.orgE<gt>.

=head1 COPYRIGHT AND LICENCE

This software is copyright (c) 2011-2014 by Michael G Schwern.

This software is copyright (c) 2022 by Toby Inkster.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=head1 DISCLAIMER OF WARRANTIES

THIS PACKAGE IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS OR IMPLIED
WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.

=cut
